mpas-ocean:
  run_modes:
    config_ocean_run_mode: forward
  io:
    config_write_output_on_startup: false
  time_management:
    config_stop_time: none
    config_run_duration: 0001_00:00:00
  time_integration:
    config_dt: 00:10:00
  split_explicit_ts:
    config_btr_dt: 0000_00:00:30
  hmix_del4:
    config_use_mom_del4: true
    config_mom_del4: 2.0e14
  cvmix:
    config_use_cvmix_convection: true
    config_use_cvmix_shear: true
    config_cvmix_shear_mixing_scheme: KPP
    config_use_cvmix_kpp: true
    config_cvmix_kpp_matching: MatchBoth
    config_cvmix_kpp_interpolationOMLType: cubic
  eos:
    config_eos_type: linear
  eos_linear:
    config_eos_linear_beta: 0.01
  frazil_ice:
    config_use_frazil_ice_formation: true
  forcing:
    config_use_bulk_wind_stress: true
  tracer_forcing_activeTracers:
    config_use_activeTracers_surface_bulk_forcing: true
    config_use_activeTracers_surface_restoring: true
    config_use_activeTracers_interior_restoring: true
  debug:
    config_compute_active_tracer_budgets: true
  AM_conservationCheck:
    config_AM_conservationCheck_enable: true
    config_AM_conservationCheck_compute_on_startup: true
    config_AM_conservationCheck_write_on_startup: true
  streams:
    mesh:
      filename_template: initial_state.nc
    input:
      filename_template: initial_state.nc
    restart: {}
    KPP_testing:
      filename_template: KPP.nc
      output_interval: 0000_00:00:01
    mixedLayerDepthsOutput:
      contents:
      - xtime
      - dThreshMLD
      - tThreshMLD
    output:
      type: output
      filename_template: output.nc
      output_interval: 0000_00:00:01
      clobber_mode: truncate
      contents:
      - tracers
      - xtime
      - daysSinceStartOfSim
      - ssh
      - bottomDepth
      - zMid
      - zTop
      - normalVelocity
      - layerThickness
      - kineticEnergyCell
      - vertVelocityTop
      - relativeVorticityCell
      - accumulatedFrazilIceMass
      - accumulatedFrazilIceSalinity
      - frazilSurfacePressure
      - frazilLayerThicknessTendency
      - frazilTemperatureTendency
      - frazilSalinityTendency
      - activeTracerSurfaceFluxTendency
      - activeTracerVerticalAdvectionTendency
      - activeTracerVerticalAdvectionTopFlux
      - activeTracersTend
      - temperatureShortWaveTendency
      - activeTracerVertMixTendency
    forcing_data:
      type: input
      filename_template: forcing.nc
      input_interval: initial_only
      contents:
      - tracersSurfaceRestoringFields
      - tracersInteriorRestoringFields
      - tracersExponentialDecayFields
      - tracersIdealAgeFields
      - tracersTTDFields
      - windStressZonal
      - windStressMeridional
      - landIceSurfaceTemperature
      - atmosphericPressure
      - latentHeatFlux
      - sensibleHeatFlux
      - shortWaveHeatFlux
      - evaporationFlux
      - rainFlux
    conservationCheckOutput:
      type: output
      filename_template: conservationCheck.nc
      filename_interval: none
      clobber_mode: truncate
      packages: conservationCheckAMPKG
      output_interval: 0000_00:00:01
      contents:
      - xtime
      - daysSinceStartOfSim
      - initialEnergy
      - finalEnergy
      - energyChange
      - netEnergyFlux
      - absoluteEnergyError
      - relativeEnergyError
      - initialMass
      - finalMass
      - massChange
      - netMassFlux
      - absoluteMassError
      - relativeMassError
      - initialSalt
      - finalSalt
      - saltChange
      - netSaltFlux
      - absoluteSaltError
      - relativeSaltError
      - accumulatedLatentHeatFlux
      - accumulatedSensibleHeatFlux
      - accumulatedLongWaveHeatFluxUp
      - accumulatedLongWaveHeatFluxDown
      - accumulatedShortWaveHeatFlux
      - accumulatedSeaIceHeatFlux
      - accumulatedMeltingSnowHeatFlux
      - accumulatedMeltingIceRunoffHeatFlux
      - accumulatedRemovedIceRunoffHeatFlux
      - accumulatedIcebergHeatFlux
      - accumulatedFrazilHeatFlux
      - accumulatedLandIceHeatFlux
      - accumulatedLandIceFrazilHeatFlux
      - accumulatedRainTemperatureFlux
      - accumulatedEvapTemperatureFlux
      - accumulatedSeaIceTemperatureFlux
      - accumulatedRiverRunoffTemperatureFlux
      - accumulatedSubglacialRunoffTemperatureFlux
      - accumulatedIcebergTemperatureFlux
      - accumulatedRainFlux
      - accumulatedSnowFlux
      - accumulatedEvaporationFlux
      - accumulatedSeaIceFlux
      - accumulatedRiverRunoffFlux
      - accumulatedSubglacialRunoffFlux
      - accumulatedIceRunoffFlux
      - accumulatedRemovedRiverRunoffFlux
      - accumulatedRemovedIceRunoffFlux
      - accumulatedIcebergFlux
      - accumulatedFrazilFlux
      - accumulatedLandIceFlux
      - accumulatedLandIceFrazilFlux
      - accumulatedSeaIceSalinityFlux
      - accumulatedFrazilSalinityFlux
      - accumulatedSubglacialRunoffSalinityFlux
      - initialCarbon
      - finalCarbon
      - carbonChange
      - netCarbonFlux
      - absoluteCarbonError
      - relativeCarbonError
      - accumulatedAbsoluteCarbonError
      - accumulatedRelativeCarbonError
#    conservationCheckRestart:
#      type: input;output
#      filename_template: restarts/restart.AM.conservationCheck.$Y-$M-$D_$h.$m.$s.nc
#      filename_interval: output_interval
#      clobber_mode: replace_files
#      packages: conservationCheckAMPKG
#      input_interval: initial_only
#      output_interval: 0001_00:00:00
